// crates/sumo-kb/src/kif_store.rs
//
// Ported from sumo-parser-core/src/store.rs.
// Key change: explicit `next_symbol_id` and `next_sentence_id` counters replace
// implicit Vec::len() -based IDs, enabling `seed_counters()` so the persist
// layer can set the in-memory counter to continue from the LMDB max, eliminating
// ID remapping at commit time.
//
// DisplayWrapper types (ElementDisplay, SentenceDisplay) live here.

use std::{collections::HashMap, fmt};
use inline_colorization::*;

use crate::KbError;
use crate::parse::ast::{Span, AstNode, OpKind};
use crate::types::{Element, Literal, Sentence, SentenceId, Symbol, SymbolId};
use smallvec::SmallVec;

// -- KifStore ------------------------------------------------------------------

/// The raw parsed store -- sentences, symbols, and indices.
///
/// Populated incrementally by [`load_kif`].  Symbol and sentence IDs are
/// stable `u64` values driven by explicit atomic-style counters that can be
/// seeded from LMDB on `open()`, ensuring no ID collision between in-memory
/// and persisted data.
///
/// Taxonomy edges (subclass/instance/subrelation/subAttribute) are derived
/// semantic structure and live in [`SemanticLayer`], not here.
#[derive(Debug, Default)]
pub(crate) struct KifStore {
    pub sentences:    Vec<Sentence>,
    pub symbols:      HashMap<String, SymbolId>,
    pub symbol_data:  Vec<Symbol>,

    /// Root (top-level) sentence ids -- in insertion order.
    pub roots:        Vec<SentenceId>,
    /// All sub-sentence ids (nested inside root sentences).
    pub sub_sentences: Vec<SentenceId>,
    /// Root sentences grouped by file tag.
    pub file_roots:   HashMap<String, Vec<SentenceId>>,
    /// Root sentences indexed by head predicate name.
    pub head_index:   HashMap<String, Vec<SentenceId>>,

    /// SentenceId -> Vec index.  Decouples stable IDs from Vec positions so that
    /// seeded counters (e.g. starting at 1000 after an LMDB load) do not cause
    /// out-of-bounds accesses.
    sent_idx:         HashMap<SentenceId, usize>,
    /// SymbolId -> Vec index into symbol_data.
    sym_idx:          HashMap<SymbolId, usize>,

    /// Explicit counter for next SymbolId -- seeded from LMDB max on open().
    next_symbol_id:   u64,
    /// Explicit counter for next SentenceId -- seeded from LMDB max on open().
    next_sentence_id: u64,
    /// Internal counter for variable scope disambiguation (not persisted).
    scope_counter:    u64,
}

impl KifStore {
    // -- Counter seeding -------------------------------------------------------

    /// Seed the ID counters from the LMDB max values.  Called by `open()` after
    /// loading all existing formulas from the DB so that any new IDs assigned
    /// in-memory are guaranteed not to collide with existing persisted IDs.
    pub(crate) fn seed_counters(&mut self, next_sym: u64, next_sent: u64) {
        self.next_symbol_id   = next_sym;
        self.next_sentence_id = next_sent;
        log::debug!(target: "sumo_kb::kif_store",
            "ID counters seeded: next_symbol_id={}, next_sentence_id={}",
            next_sym, next_sent);
    }

    // -- Symbol table ---------------------------------------------------------

    /// Intern a symbol name.  Returns the existing id on cache hit,
    /// allocates a new stable id on miss.
    pub(crate) fn intern(&mut self, name: &str) -> SymbolId {
        if let Some(&id) = self.symbols.get(name) {
            return id;
        }
        let id  = self.next_symbol_id;
        let idx = self.symbol_data.len();
        self.next_symbol_id += 1;
        self.symbol_data.push(Symbol {
            name: name.to_owned(),
            head_sentences: Vec::new(),
            all_sentences:  Vec::new(),
            is_skolem:      false,
            skolem_arity:   None,
        });
        self.symbols.insert(name.to_owned(), id);
        self.sym_idx.insert(id, idx);
        log::debug!(target: "sumo_kb::kif_store", "interned symbol '{}' -> id={}", name, id);
        id
    }

    #[cfg(feature = "cnf")]
    /// Intern a Skolem symbol (generated by CNF conversion).
    pub(crate) fn intern_skolem(&mut self, name: &str, arity: Option<usize>) -> SymbolId {
        if let Some(&id) = self.symbols.get(name) {
            return id;
        }
        let id  = self.next_symbol_id;
        let idx = self.symbol_data.len();
        self.next_symbol_id += 1;
        self.symbol_data.push(Symbol {
            name: name.to_owned(),
            head_sentences: Vec::new(),
            all_sentences:  Vec::new(),
            is_skolem:      true,
            skolem_arity:   arity,
        });
        self.symbols.insert(name.to_owned(), id);
        self.sym_idx.insert(id, idx);
        log::debug!(target: "sumo_kb::kif_store",
            "interned skolem '{}' (arity={:?}) -> id={}", name, arity, id);
        id
    }

    pub(crate) fn sym_name(&self, id: SymbolId) -> &str {
        let idx = self.sym_idx[&id];
        &self.symbol_data[idx].name
    }

    pub(crate) fn sym_id(&self, name: &str) -> Option<SymbolId> {
        self.symbols.get(name).copied()
    }

    /// Resolve a SentenceId to its Vec index (panics if not found).
    #[inline]
    pub(crate) fn sent_idx(&self, sid: SentenceId) -> usize {
        self.sent_idx[&sid]
    }

    /// Return true if `sid` is a known sentence.
    #[inline]
    pub(crate) fn has_sentence(&self, sid: SentenceId) -> bool {
        self.sent_idx.contains_key(&sid)
    }

    /// Resolve a SymbolId to its Vec index (panics if not found).
    #[inline]
    fn sym_vec_idx(&self, id: SymbolId) -> usize {
        self.sym_idx[&id]
    }

    /// Return a reference to the sent_idx map (used by persist::load).
    #[cfg(feature = "persist")]
    pub(crate) fn sent_idx_map(&self) -> &HashMap<SentenceId, usize> {
        &self.sent_idx
    }

    /// Insert a stable SentenceId -> Vec position mapping (used by persist::load).
    #[cfg(feature = "persist")]
    pub(crate) fn insert_sent_idx(&mut self, sid: SentenceId, vec_pos: usize) {
        self.sent_idx.insert(sid, vec_pos);
    }

    /// Insert a stable SymbolId -> Vec position mapping (used by persist::load).
    #[cfg(feature = "persist")]
    pub(crate) fn insert_sym_idx(&mut self, sym_id: SymbolId, vec_pos: usize) {
        self.sym_idx.insert(sym_id, vec_pos);
    }

    // -- Sentence allocation ---------------------------------------------------

    fn alloc_sentence(&mut self, sentence: Sentence) -> SentenceId {
        let id  = self.next_sentence_id;
        let idx = self.sentences.len();
        self.next_sentence_id += 1;
        self.sentences.push(sentence);
        self.sent_idx.insert(id, idx);
        log::trace!(target: "sumo_kb::kif_store", "allocated sentence id={} at vec[{}]", id, idx);
        id
    }

    fn next_scope(&mut self) -> u64 {
        let id = self.scope_counter;
        self.scope_counter += 1;
        id
    }

    // Load (syntax pass)

    /// Process a list of top-level AST nodes into this store, tagging them
    /// with `file`.  Returns any stoppable errors found.
    pub(crate) fn load(&mut self, nodes: &[AstNode], file: &str) -> Vec<(Span, KbError)> {
        let mut errors: Vec<(Span, KbError)> = Vec::new();
        for node in nodes {
            if let AstNode::List { .. } = node {
                let ctx = ScopeCtx { default: self.next_scope(), overrides: HashMap::new() };
                if let Some(sent_id) = self.build_sentence(&ctx, node, file, &mut errors, true) {
                    log::trace!(target: "sumo_kb::kif_store",
                        "registered root sentence id={}", sent_id);
                    self.roots.push(sent_id);
                    self.file_roots.entry(file.to_owned()).or_default().push(sent_id);
                    if let Some(head_id) = self.sentences[self.sent_idx(sent_id)].head_symbol() {
                        let head_name = self.sym_name(head_id).to_owned();
                        self.head_index.entry(head_name).or_default().push(sent_id);
                        let head_vec_idx = self.sym_vec_idx(head_id);
                        self.symbol_data[head_vec_idx].head_sentences.push(sent_id);
                    }
                }
            }
        }
        errors
    }

    fn build_sentence(
        &mut self,
        ctx: &ScopeCtx,
        node: &AstNode,
        file: &str,
        errors: &mut Vec<(Span, KbError)>,
        top_level: bool,
    ) -> Option<SentenceId> {
        let (elements_ast, span) = match node {
            AstNode::List { elements, span } => (elements, span.clone()),
            _ => return None,
        };

        if elements_ast.is_empty() {
            if top_level {
                unreachable!("The parser should have found and rejected empty sentences");
            } else {
                let sid = self.alloc_sentence(Sentence { elements: SmallVec::new(), file: file.to_owned(), span });
                return Some(sid);
            }
        }

        if top_level {
            let first = &elements_ast[0];
            if !matches!(first, AstNode::Symbol { .. } | AstNode::Variable { .. } | AstNode::RowVariable { .. } | AstNode::Operator { .. }) {
                unreachable!("The parser should have caught sentences which did not start with a symbol");
            }
        }

        for (i, el) in elements_ast.iter().enumerate() {
            if i > 0 {
                if let AstNode::Operator { .. } = el {
                    unreachable!("The parser should have caught sentences where the symbol did not appear in the first term of a sentence");
                }
            }
        }

        // If this is a quantifier, build a child context for its body.
        let child_ctx;
        let body_ctx = if matches!(elements_ast.get(0), Some(AstNode::Operator { op: OpKind::Exists | OpKind::ForAll, .. })) {
            let bound: Vec<String> = match elements_ast.get(1) {
                Some(AstNode::List { elements, .. }) => {
                    elements.iter().map(|e| match e {
                        AstNode::Variable { name, .. }
                        | AstNode::RowVariable { name, .. } => name.clone(),
                        _ => unreachable!("The parser should have caught a quantifier variable sentence"),
                    }).collect()
                }
                _ => unreachable!("The parser should have caught a quantifier variable sentence"),

            };
            let q_scope = self.next_scope();
            child_ctx = ScopeCtx {
                default:   ctx.default,
                overrides: ctx.overrides.clone().into_iter()
                    .chain(bound.into_iter().map(|v| (v, q_scope)))
                    .collect(),
            };
            &child_ctx
        } else {
            ctx
        };

        let mut elements: SmallVec<[Element; 4]> = SmallVec::with_capacity(elements_ast.len());
        for el in elements_ast {
            let elem = self.build_element(body_ctx, el, file, errors)?;
            elements.push(elem);
        }
        let sid = self.alloc_sentence(Sentence { elements, file: file.to_owned(), span });
        Some(sid)
    }

    fn build_element(
        &mut self,
        ctx: &ScopeCtx,
        node: &AstNode,
        file: &str,
        errors: &mut Vec<(Span, KbError)>,
    ) -> Option<Element> {
        log::trace!(target: "sumo_kb::kif_store", "building element: {}", node);
        match node {
            AstNode::Symbol { name, .. } => Some(Element::Symbol(self.intern(name))),
            AstNode::Variable { name, .. } => {
                let scope = ctx.scope_for(name);
                Some(Element::Variable { id: self.intern(&format!("{}__{}", name, scope)), name: name.clone(), is_row: false })
            }
            AstNode::RowVariable { name, .. } => {
                let scope = ctx.scope_for(name);
                Some(Element::Variable { id: self.intern(&format!("{}__{}", name, scope)), name: name.clone(), is_row: true })
            }
            AstNode::Str    { value, .. } => Some(Element::Literal(Literal::Str(value.clone()))),
            AstNode::Number { value, .. } => Some(Element::Literal(Literal::Number(value.clone()))),
            AstNode::Operator { op, .. } => Some(Element::Op(op.clone())),
            AstNode::List { .. } => {
                match self.build_sentence(ctx, node, file, errors, false) {
                    Some(sub_id) => { self.sub_sentences.push(sub_id); Some(Element::Sub(sub_id)) }
                    None => None,
                }
            }
        }
    }

    // -- remove_file -----------------------------------------------------------

    /// Remove all sentences tagged with `file`.
    /// Remove the `file_roots` mapping for `file` without touching `roots` or `sentences`.
    /// Used after promotion to detach sentences from their session tag
    /// while keeping them as in-memory axioms.
    pub(crate) fn clear_file_roots(&mut self, file: &str) {
        self.file_roots.remove(file);
    }

    pub(crate) fn remove_file(&mut self, file: &str) {
        let ids_to_remove: Vec<SentenceId> = self.file_roots.remove(file).unwrap_or_default();
        if ids_to_remove.is_empty() { return; }
        let id_set: std::collections::HashSet<SentenceId> = ids_to_remove.iter().copied().collect();
        self.roots.retain(|id| !id_set.contains(id));
        for v in self.head_index.values_mut() { v.retain(|id| !id_set.contains(id)); }
        self.head_index.retain(|_, v| !v.is_empty());
        for &sid in &ids_to_remove {
            if self.sent_idx.contains_key(&sid) {
                let vec_idx = self.sent_idx(sid);
                self.sentences[vec_idx].elements.clear();
            }
        }
        self.prune_orphaned_symbols(&id_set);
        log::debug!(target: "sumo_kb::kif_store",
            "removed {} sentences from file '{}'", ids_to_remove.len(), file);
    }

    fn prune_orphaned_symbols(&mut self, _removed_ids: &std::collections::HashSet<SentenceId>) {
        let mut referenced = std::collections::HashSet::new();
        for &sid in &self.roots { self.collect_symbols(sid, &mut referenced); }
        let to_remove: Vec<String> = self.symbols.keys()
            .filter(|name| !referenced.contains(self.symbols.get(*name).unwrap()))
            .cloned().collect();
        for name in to_remove {
            if let Some(id) = self.symbols.remove(&name) {
                let sym_vec_idx = self.sym_vec_idx(id);
                self.symbol_data[sym_vec_idx].head_sentences.clear();
                self.symbol_data[sym_vec_idx].all_sentences.clear();
            }
        }
    }

    fn collect_symbols(&self, sent_id: SentenceId, out: &mut std::collections::HashSet<SymbolId>) {
        let sentence = &self.sentences[self.sent_idx(sent_id)];
        for el in &sentence.elements {
            match el {
                Element::Symbol(id) => { out.insert(*id); }
                Element::Sub(sub_id) => self.collect_symbols(*sub_id, out),
                _ => {}
            }
        }
    }

    // -- Lookup helpers --------------------------------------------------------

    pub(crate) fn by_head(&self, head: &str) -> &[SentenceId] {
        self.head_index.get(head).map(|v| v.as_slice()).unwrap_or(&[])
    }

    /// Pattern lookup.  Tokens: literal = exact match, `_` = any one element,
    /// `_N` = consume remaining.
    pub(crate) fn lookup(&self, pattern: &str) -> Vec<SentenceId> {
        let tokens: Vec<&str> = pattern.split_whitespace().collect();
        if tokens.is_empty() { return self.roots.clone(); }
        let candidates: Box<dyn Iterator<Item = &SentenceId>> = if tokens[0] != "_" {
            match self.head_index.get(tokens[0]) { Some(ids) => Box::new(ids.iter()), None => return Vec::new() }
        } else { Box::new(self.roots.iter()) };
        candidates.copied().filter(|&sid| self.matches_pattern(sid, &tokens)).collect()
    }

    fn matches_pattern(&self, sid: SentenceId, tokens: &[&str]) -> bool {
        let elems = &self.sentences[self.sent_idx(sid)].elements;
        let (mut e_idx, mut t_idx) = (0, 0);
        while t_idx < tokens.len() {
            let tok = tokens[t_idx];
            if tok == "_" {
                if e_idx >= elems.len() { return false; }
                e_idx += 1; t_idx += 1;
            } else if tok.starts_with('_') && tok[1..].parse::<usize>().is_ok() {
                return true;
            } else {
                if e_idx >= elems.len() { return false; }
                if !self.elem_matches_name(&elems[e_idx], tok) { return false; }
                e_idx += 1; t_idx += 1;
            }
        }
        e_idx == elems.len()
    }

    fn elem_matches_name(&self, elem: &Element, name: &str) -> bool {
        match elem {
            Element::Symbol(id)              => self.sym_name(*id) == name,
            Element::Op(op)                  => op.name() == name,
            Element::Variable { name: n, .. }=> n == name,
            Element::Literal(Literal::Number(n)) => n == name,
            Element::Literal(Literal::Str(s))    => s == name,
            Element::Sub(_)                  => false,
        }
    }
}

// -- Scope context -------------------------------------------------------------

struct ScopeCtx {
    default:   u64,
    overrides: HashMap<String, u64>,
}
impl ScopeCtx {
    fn scope_for(&self, var_name: &str) -> u64 {
        self.overrides.get(var_name).copied().unwrap_or(self.default)
    }
}

// -- Display wrappers ----------------------------------------------------------

pub(crate) struct ElementDisplay<'a> {
    pub element:   &'a Element,
    pub store:     &'a KifStore,
    pub indent:    usize,
    pub highlight: bool,
}

impl<'a> fmt::Display for ElementDisplay<'a> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        if self.highlight { write!(f, "{style_bold}{style_underline}")?; }
        let res = match self.element {
            Element::Symbol(id) => {
                let name = self.store.sym_name(*id);
                if name.chars().next().map_or(false, |c| c.is_uppercase()) {
                    write!(f, "{color_yellow}{}{color_reset}", name)
                } else {
                    write!(f, "{color_blue}{}{color_reset}", name)
                }
            }
            Element::Variable { name, is_row: false, .. } => write!(f, "{color_magenta}?{}{color_reset}", name),
            Element::Variable { name, is_row: true,  .. } => write!(f, "{color_magenta}@{}{color_reset}", name),
            Element::Literal(Literal::Str(s))    => write!(f, "{}", s),
            Element::Literal(Literal::Number(n)) => write!(f, "{color_green}{}{color_reset}", n),
            Element::Op(op)                      => write!(f, "{color_cyan}{}{color_reset}", op),
            Element::Sub(sid)                    => SentenceDisplay::raw(*sid, self.store, self.indent, -1).fmt(f),
        };
        if self.highlight { write!(f, "{style_reset}") } else { res }
    }
}

pub(crate) struct SentenceDisplay<'a> {
    pub sid:           SentenceId,
    pub store:         &'a KifStore,
    pub indent:        usize,
    pub show_gutter:   bool,
    pub highlight_arg: i32,
}

impl<'a> SentenceDisplay<'a> {
    pub(crate) fn raw(sid: SentenceId, store: &'a KifStore, indent: usize, arg: i32) -> Self {
        Self { sid, store, indent, show_gutter: false, highlight_arg: arg }
    }
    fn to_raw_string(&self, arg: i32) -> String {
        SentenceDisplay::raw(self.sid, self.store, 0, arg).to_string()
    }
}

impl<'a> fmt::Display for SentenceDisplay<'a> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        if self.show_gutter {
            let content  = self.to_raw_string(self.highlight_arg);
            let line_no  = self.store.sentences[self.store.sent_idx(self.sid)].span.line;
            let num_str  = line_no.to_string();
            let width    = num_str.len().min(6);
            let blank    = " ".repeat(width);
            for (i, line) in content.lines().enumerate() {
                if i > 0 { writeln!(f)?; }
                if i == 0 { write!(f, "{:>width$} | {}", line_no, line, width = width)?; }
                else       { write!(f, "{} | {}", blank, line)?; }
            }
            return Ok(());
        }
        let sentence     = &self.store.sentences[self.store.sent_idx(self.sid)];
        let child_indent = self.indent + 1;
        write!(f, "(")?;
        for (i, el) in sentence.elements.iter().enumerate() {
            let highlight = self.highlight_arg == i as i32;
            if i == 0 {
                ElementDisplay { element: el, store: self.store, indent: child_indent, highlight }.fmt(f)?;
            } else if matches!(el, Element::Sub(_)) {
                write!(f, "\n{}", "  ".repeat(child_indent))?;
                ElementDisplay { element: el, store: self.store, indent: child_indent, highlight }.fmt(f)?;
            } else {
                write!(f, " ")?;
                ElementDisplay { element: el, store: self.store, indent: child_indent, highlight }.fmt(f)?;
            }
        }
        write!(f, ")")
    }
}

// -- Plain-text KIF formatter -------------------------------------------------

/// Recursively format a sentence as plain KIF text (no ANSI escapes).
pub(crate) fn sentence_to_plain_kif(sid: SentenceId, store: &KifStore) -> String {
    let sentence = &store.sentences[store.sent_idx(sid)];
    let mut out = String::from("(");
    for (i, elem) in sentence.elements.iter().enumerate() {
        if i > 0 { out.push(' '); }
        match elem {
            Element::Symbol(id) => out.push_str(store.sym_name(*id)),
            Element::Variable { name, is_row: false, .. } => {
                out.push('?');
                out.push_str(name);
            }
            Element::Variable { name, is_row: true, .. } => {
                out.push('@');
                out.push_str(name);
            }
            Element::Literal(Literal::Str(s))    => out.push_str(s),
            Element::Literal(Literal::Number(n)) => out.push_str(n),
            Element::Op(op)                      => out.push_str(op.name()),
            Element::Sub(sub_sid)                => out.push_str(&sentence_to_plain_kif(*sub_sid, store)),
        }
    }
    out.push(')');
    out
}

// Top-level load_kif

/// Parse `text` (tagged as `file`) into `store`.  Returns hard parse errors.
///
/// Formulas containing row variables (`@VAR`) are automatically expanded into
/// up to [`crate::row_vars::MAX_ARITY`] concrete variants before being stored.
/// This follows the approach of Java's `RowVars.expandRowVars`.
pub(crate) fn load_kif(store: &mut KifStore, text: &str, file: &str) -> Vec<(Span, KbError)> {
    use crate::parse::Parser;
    let mut errors: Vec<(Span, KbError)> = Vec::new();

    let (nodes, parse_err) = Parser::Kif.parse(text, file);
    errors.extend(parse_err.into_iter().map(|(span, p)| { (span, KbError::Parse(p)) }));
    errors.extend(store.load(&nodes, file));
    log::info!(target: "sumo_kb::kif_store",
        "loaded '{}': {} root sentences, {} errors", file, store.roots.len(), errors.len());
    errors
}

// -- Tests ---------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    fn store_from(kif: &str) -> KifStore {
        let mut store = KifStore::default();
        let errors = load_kif(&mut store, kif, "test");
        assert!(errors.is_empty(), "load errors: {:?}", errors);
        store
    }

    #[test]
    fn basic_load() {
        let store = store_from("(subclass Human Animal)");
        assert_eq!(store.roots.len(), 1);
        assert!(store.symbols.contains_key("subclass"));
        assert!(store.symbols.contains_key("Human"));
        assert!(store.symbols.contains_key("Animal"));
    }

    #[test]
    fn stable_ids_incremental() {
        let mut store = KifStore::default();
        load_kif(&mut store, "(subclass Human Animal)", "a");
        let n_sym_before  = store.next_symbol_id;
        let n_sent_before = store.next_sentence_id;
        load_kif(&mut store, "(instance Fido Dog)", "b");
        assert!(store.next_symbol_id   > n_sym_before,  "symbol counter did not advance");
        assert!(store.next_sentence_id > n_sent_before, "sentence counter did not advance");
    }

    #[test]
    fn seed_counters() {
        let mut store = KifStore::default();
        store.seed_counters(1000, 500);
        load_kif(&mut store, "(subclass Dog Animal)", "test");
        // First new symbol should get id >= 1000
        let dog_id = store.sym_id("Dog").unwrap();
        assert!(dog_id >= 1000, "symbol id {} < seeded base 1000", dog_id);
    }

    #[test]
    fn head_index() {
        let store = store_from("(subclass Human Animal)\n(subclass Dog Animal)");
        assert_eq!(store.by_head("subclass").len(), 2);
    }

    #[test]
    fn pattern_lookup() {
        let store = store_from(
            "(instance subclass BinaryRelation)\n(instance instance BinaryPredicate)");
        assert_eq!(store.lookup("instance _ BinaryRelation").len(), 1);
        assert_eq!(store.lookup("instance _ _").len(), 2);
    }

    #[test]
    fn remove_file() {
        let mut store = KifStore::default();
        load_kif(&mut store, "(subclass Human Animal)", "base");
        load_kif(&mut store, "(subclass Cat Animal)",   "delta");
        assert_eq!(store.roots.len(), 2);
        store.remove_file("delta");
        assert_eq!(store.roots.len(), 1);
        assert!(!store.symbols.contains_key("Cat"));
        assert!(store.symbols.contains_key("Human"));
    }
}
