/// Generate TPTP CNF declarations from stored `Clause` data.
///
/// Vampire accepts files containing `cnf()` declarations directly, which is
/// more efficient than sending FOF (Vampire converts FOF→CNF internally).
/// Generating CNF TPTP from pre-computed clauses avoids that conversion at
/// query time.
///
/// # TPTP CNF syntax
///
/// ```tptp
/// cnf(formula_1, axiom, ( lit1 | lit2 | ... )).
/// cnf(formula_2, hypothesis, ( ~lit1 | lit2 )).
/// ```
///
/// Variables in CNF are universally quantified by convention (no explicit
/// quantifier needed in TPTP CNF format).

use std::collections::HashSet;

use log;

use crate::env::LmdbEnv;
use crate::schema::{CnfLiteral, CnfTerm, Clause, FormulaId};
use crate::StoreError;

// TPTP naming constants (mirror sumo_parser_core::tptp)
const SYM_PFX: &str = "s__";
const VAR_PFX: &str = "V__";
const MENTION: &str = "__m";
const HOLDS:   &str = "s__holds";

// ── Public entry point ────────────────────────────────────────────────────────

/// Generate TPTP CNF for all formulas in the DB (base KB + optional session).
///
/// * `session` — include only formulas from this session as `hypothesis`;
///               `None` → all sessions' formulas are hypotheses.
///
/// Returns a TPTP string ready to write to a file.
pub fn db_to_tptp_cnf(
    env:     &LmdbEnv,
    kb_name: &str,
    session: Option<&str>,
) -> Result<String, StoreError> {
    let txn = env.read_txn()?;

    let formulas = env.all_formulas(&txn)?;
    log::info!(
        "db_to_tptp_cnf: generating TPTP CNF for {} formula(s), session={:?}",
        formulas.len(), session
    );

    // Collect session formula IDs
    let session_ids: HashSet<FormulaId> = if let Some(s) = session {
        env.sessions.get(&txn, s)?.unwrap_or_default().into_iter().collect()
    } else {
        // All session formulas
        // Mark all formulas that have a session
        formulas.iter()
            .filter(|f| f.session.is_some())
            .map(|f| f.id)
            .collect()
    };

    // Build symbol name lookup: id → name
    let syms = env.all_symbols(&txn)?;
    let sym_names: std::collections::HashMap<u64, String> =
        syms.into_iter().map(|s| (s.id, s.name)).collect();

    let mut lines: Vec<String> = Vec::new();
    lines.push(format!(
        "% SUMO KB '{}' — pre-computed CNF\n% Generated by sumo-store\n",
        kb_name
    ));

    let mut written: HashSet<String> = HashSet::new();
    let mut idx = 1usize;

    for formula in &formulas {
        if formula.clauses.is_empty() {
            log::debug!("db_to_tptp_cnf: formula {} has no CNF clauses, skipping", formula.id);
            continue;
        }

        let role = if session_ids.contains(&formula.id) { "hypothesis" } else { "axiom" };

        for clause in &formula.clauses {
            let tptp = clause_to_tptp_str(clause, &sym_names);
            if tptp.is_empty() || written.contains(&tptp) { continue; }
            written.insert(tptp.clone());
            lines.push(format!("cnf(kb_{}_{},{},\n    ( {} )).", kb_name, idx, role, tptp));
            idx += 1;
        }
    }

    Ok(lines.join("\n"))
}

// ── Clause → TPTP string ──────────────────────────────────────────────────────

pub fn clause_to_tptp_str(
    clause:    &Clause,
    sym_names: &std::collections::HashMap<u64, String>,
) -> String {
    if clause.literals.is_empty() {
        return String::new();
    }
    clause.literals.iter()
        .map(|lit| literal_to_tptp(lit, sym_names))
        .collect::<Vec<_>>()
        .join("\n  | ")
}

fn literal_to_tptp(
    lit:       &CnfLiteral,
    sym_names: &std::collections::HashMap<u64, String>,
) -> String {
    let atom = atom_to_tptp(&lit.pred, &lit.args, sym_names);
    if lit.positive {
        atom
    } else {
        format!("~({})", atom)
    }
}

fn atom_to_tptp(
    pred:      &CnfTerm,
    args:      &[CnfTerm],
    sym_names: &std::collections::HashMap<u64, String>,
) -> String {
    match pred {
        CnfTerm::Const(id) if *id == u64::MAX && args.len() == 2 => {
            // Equality: (a = b)
            let a = term_to_tptp(&args[0], sym_names);
            let b = term_to_tptp(&args[1], sym_names);
            format!("({} = {})", a, b)
        }
        CnfTerm::Const(id) => {
            let pred_name = tptp_sym(id, true, sym_names);
            if args.is_empty() {
                format!("{}({})", HOLDS, pred_name)
            } else {
                let arg_strs: Vec<String> = args.iter().map(|a| term_to_tptp(a, sym_names)).collect();
                format!("{}({},{} )", HOLDS, pred_name, arg_strs.join(","))
            }
        }
        CnfTerm::Var(id) => {
            let var = tptp_var(id, sym_names);
            if args.is_empty() {
                format!("{}({})", HOLDS, var)
            } else {
                let arg_strs: Vec<String> = args.iter().map(|a| term_to_tptp(a, sym_names)).collect();
                format!("{}({},{})", HOLDS, var, arg_strs.join(","))
            }
        }
        other => {
            let head = term_to_tptp(other, sym_names);
            if args.is_empty() {
                head
            } else {
                let arg_strs: Vec<String> = args.iter().map(|a| term_to_tptp(a, sym_names)).collect();
                format!("{}({})", head, arg_strs.join(","))
            }
        }
    }
}

fn term_to_tptp(
    term:      &CnfTerm,
    sym_names: &std::collections::HashMap<u64, String>,
) -> String {
    match term {
        CnfTerm::Const(id)              => tptp_sym(id, false, sym_names),
        CnfTerm::Var(id)                => tptp_var(id, sym_names),
        CnfTerm::SkolemFn { id, args }  => {
            let fn_name = tptp_sym(id, false, sym_names);
            if args.is_empty() {
                fn_name
            } else {
                let arg_strs: Vec<String> = args.iter().map(|a| term_to_tptp(a, sym_names)).collect();
                format!("{}({})", fn_name, arg_strs.join(","))
            }
        }
        CnfTerm::Num(n)  => format!("n__{}", n.replace('.', "_").replace('-', "_")),
        CnfTerm::Str(s)  => {
            let inner = &s[s.find('"').map(|i| i + 1).unwrap_or(0)
                ..s.rfind('"').unwrap_or(s.len())];
            format!("'{}'", inner.chars().filter(|&c| c != '\'').collect::<String>())
        }
    }
}

fn tptp_sym(id: &u64, mention: bool, sym_names: &std::collections::HashMap<u64, String>) -> String {
    let raw = sym_names.get(id)
        .map(|s| s.replace('.', "_").replace('-', "_"))
        .unwrap_or_else(|| format!("sym_{}", id));
    if mention {
        format!("{}{}{}", SYM_PFX, raw, MENTION)
    } else {
        format!("{}{}", SYM_PFX, raw)
    }
}

fn tptp_var(id: &u64, sym_names: &std::collections::HashMap<u64, String>) -> String {
    // Variable names in the store have the form "X@scope" — strip the scope suffix
    // for TPTP output so the variable is readable.
    let raw = sym_names.get(id).map(|s| s.as_str()).unwrap_or("V");
    // Build a unique name from the full raw string to avoid collisions
    let unique = raw.replace('@', "_at_").replace('.', "_").replace('-', "_");
    format!("{}{}", VAR_PFX, unique)
}
