// crates/core/src/syntactic/intern.rs
//
// Symbol interning + name/id lookup methods for SyntacticLayer.

use crate::types::{Symbol, SymbolId};

use super::SyntacticLayer;

impl SyntacticLayer {
    /// Intern a symbol name.  Returns the existing id on cache hit,
    /// allocates a new stable id on miss.
    pub(crate) fn intern(&mut self, name: &str) -> SymbolId {
        // If the symbol name already exists, return it
        if let Some(&id) = self.symbols.get(name) {
            return id;
        }
        // Get the next symbol id based on the counter
        let id  = self.next_symbol_id;
        // Get the local in-memory id (the index of the vector)
        let idx = self.symbol_data.len();
        // Increment the id counter
        self.next_symbol_id += 1;
        // Add a new symbol to the symbol data vector
        self.symbol_data.push(Symbol {
            name: name.to_owned(),
            head_sentences: Vec::new(),
            all_sentences:  Vec::new(),
            is_skolem:      false,
            skolem_arity:   None,
        });
        self.symbols.insert(name.to_owned(), id);
        self.sym_idx.insert(id, idx);
        #[cfg(debug_assertions)]
        crate::emit_event!(crate::progress::ProgressEvent::Log { level: crate::progress::LogLevel::Debug, target: "sigmakee_rs_core::syntactic", message: format!("interned symbol '{}' -> id={}", name, id) });
        id
    }

    /// Intern a Skolem symbol (generated by CNF conversion).
    #[cfg(feature = "cnf")]
    pub(crate) fn intern_skolem(&mut self, name: &str, arity: Option<usize>) -> SymbolId {
        if let Some(&id) = self.symbols.get(name) {
            return id;
        }
        let id  = self.next_symbol_id;
        let idx = self.symbol_data.len();
        self.next_symbol_id += 1;
        self.symbol_data.push(Symbol {
            name: name.to_owned(),
            head_sentences: Vec::new(),
            all_sentences:  Vec::new(),
            is_skolem:      true,
            skolem_arity:   arity,
        });
        self.symbols.insert(name.to_owned(), id);
        self.sym_idx.insert(id, idx);
        crate::emit_event!(crate::progress::ProgressEvent::Log { level: crate::progress::LogLevel::Debug, target: "sigmakee_rs_core::syntactic", message: format!("interned skolem '{}' (arity={:?}) -> id={}", name, arity, id) });
        id
    }

    /// Get the string name of a symbol from its ID.
    pub(crate) fn sym_name(&self, id: SymbolId) -> &str {
        let idx = self.sym_idx[&id];
        &self.symbol_data[idx].name
    }

    /// Get the symbol ID from its string name.
    pub(crate) fn sym_id(&self, name: &str) -> Option<SymbolId> {
        self.symbols.get(name).copied()
    }

    /// Return true if `id` is a known symbol.
    #[inline]
    pub(crate) fn has_symbol(&self, id: SymbolId) -> bool {
        self.sym_idx.contains_key(&id)
    }

    /// O(1) `SymbolId -> &Symbol` lookup.  Returns `None` for ids
    /// not in the intern table (e.g. stale ids from removed files).
    #[inline]
    pub(crate) fn symbol_of(&self, id: SymbolId) -> Option<&Symbol> {
        self.sym_idx.get(&id).map(|&idx| &self.symbol_data[idx])
    }

    /// Resolve a SymbolId to its Vec index (panics if not found).
    #[inline]
    pub(in crate::syntactic) fn sym_vec_idx(&self, id: SymbolId) -> usize {
        self.sym_idx[&id]
    }
}
